# Generated by Django 4.2.1 on 2023-05-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_position', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinate', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='drone.position')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='drone.position')),
            ],
        ),
    ]
